{% set name = "saa" %}
{% set version = "0.0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/saa-{{ version }}.tar.gz
  sha256: 9a54b12aacf5dd6f2869cde95b5ee9e87c30255961c013e035498519c1838d2a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - poetry-core
    - pip
  run:
    - python >=3.9

test:
  imports:
    - saa
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Proteusiq/saa
  summary: Converting time into natural language phrases
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
